### ISSUE TITLE
Dragon sometimes counts towards death instead of score

### ISSUE THREAD

**Issue by Jeepingitup** [adsads/NASDRAGON#5]
I ran over a dragon and it killed me instead of counting it as a score.

**Comment by adsads** [comment]
Not a bug: its a feature, Dragons are known to be deadly

**Comment by Jeepingitup** [comment]
I hit it with a 200mph 2000lb racecar. How does the dragon not die? Also why is it only some dragons? Can we get an indicator on which dragons will kill us? Also how do we kill this so called dragon
